const STAFF_ROUTE_PREFIX = "/staff";
const ATTENDEE_ROUTE_PREFIX = "/attendee";
const ATTENDEE_AUTH_ROUTE_PREFIX = "/auth";
const STAFF_AUTH_ROUTE_PREFIX = "/staff/auth";

const PUBLIC_ROUTES = [
  `${ATTENDEE_AUTH_ROUTE_PREFIX}/login`,
  `${ATTENDEE_AUTH_ROUTE_PREFIX}/signup`,
  `${ATTENDEE_AUTH_ROUTE_PREFIX}/invite-request`,
  `${STAFF_AUTH_ROUTE_PREFIX}/login`,
  `${STAFF_AUTH_ROUTE_PREFIX}/signup`,
  `${STAFF_AUTH_ROUTE_PREFIX}/invite-request`,
];

const ATTENDEE_LOGIN_ROUTE = `${ATTENDEE_AUTH_ROUTE_PREFIX}/login`;
const STAFF_LOGIN_ROUTE = `${STAFF_AUTH_ROUTE_PREFIX}/login`;
const STAFF_HOME_ROUTE = `${STAFF_ROUTE_PREFIX}/`;
const ATTENDEE_HOME_ROUTE = `${ATTENDEE_ROUTE_PREFIX}/`;

export {
  STAFF_ROUTE_PREFIX,
  ATTENDEE_ROUTE_PREFIX,
  ATTENDEE_AUTH_ROUTE_PREFIX,
  STAFF_AUTH_ROUTE_PREFIX,
  PUBLIC_ROUTES,
  ATTENDEE_LOGIN_ROUTE,
  STAFF_LOGIN_ROUTE,
  STAFF_HOME_ROUTE,
  ATTENDEE_HOME_ROUTE,
};
