const teams = [
  { id: "operations", label: "Operations" },
  { id: "programming", label: "Programming" },
  { id: "hospitality", label: "Hospitality" },
  { id: "security", label: "Security" },
  { id: "logistics", label: "Logistics" },
] as const;

const staffTypes = [
  { id: "ops-command", label: "Ops command lead" },
  { id: "ops-runner", label: "Ops floor runner" },
  { id: "programming-producer", label: "Programming producer" },
  { id: "content-host", label: "Content host" },
  { id: "hospitality-suite", label: "Hospitality suite host" },
  { id: "security-shift", label: "Security shift lead" },
  { id: "logistics-fleet", label: "Logistics fleet chief" },
] as const;

const peopleDirectory = [
  {
    id: "alex-chen",
    full_name: "Alex Chen",
    email: "alex.chen@btic.co",
    team: "operations",
    accessRole: "staff",
    staffType: "ops-command",
    status: "active",
    source: "Master upload · Clean",
    lastUpdate: "Today · 09:12 AM",
  },
  {
    id: "maya-patel",
    full_name: "Maya Patel",
    email: "maya.patel@btic.co",
    team: "programming",
    accessRole: "staff",
    staffType: "programming-producer",
    status: "active",
    source: "Team import",
    lastUpdate: "Today · 08:54 AM",
  },
  {
    id: "leo-carter",
    full_name: "Leo Carter",
    email: "leo.carter@btic.co",
    team: "hospitality",
    accessRole: "staff",
    staffType: "hospitality-suite",
    status: "active",
    source: "Manual promotion",
    lastUpdate: "Yesterday · 10:44 PM",
  },
  {
    id: "lara-cho",
    full_name: "Lara Cho",
    email: "lara.cho@btic.co",
    team: "security",
    accessRole: "staff",
    staffType: "security-shift",
    status: "active",
    source: "Master upload · Clean",
    lastUpdate: "Yesterday · 09:20 PM",
  },
  {
    id: "opal-reed",
    full_name: "Opal Reed",
    email: "opal.reed@btic.co",
    team: "logistics",
    accessRole: "staff",
    staffType: "logistics-fleet",
    status: "active",
    source: "Fleet update import",
    lastUpdate: "Today · 07:38 AM",
  },
  {
    id: "natalie-young",
    full_name: "Natalie Young",
    email: "natalie.young@btic.co",
    team: "programming",
    accessRole: "attendee",
    status: "invited",
    source: "Self-service RSVP",
    lastUpdate: "Today · 07:05 AM",
  },
  {
    id: "jamie-bowen",
    full_name: "Jamie Bowen",
    email: "jamie.bowen@btic.co",
    team: "hospitality",
    accessRole: "attendee",
    status: "active",
    source: "Master upload · Clean",
    lastUpdate: "Yesterday · 11:12 PM",
  },
  {
    id: "dahlia-ortiz",
    full_name: "Dahlia Ortiz",
    email: "dahlia.ortiz@btic.co",
    team: "operations",
    accessRole: "staff",
    staffType: "ops-runner",
    status: "invited",
    source: "Team import · Pending",
    lastUpdate: "Today · 06:54 AM",
  },
  {
    id: "kofi-diaz",
    full_name: "Kofi Diaz",
    email: "kofi.diaz@btic.co",
    team: "security",
    accessRole: "staff",
    staffType: "security-shift",
    status: "active",
    source: "Manual promotion",
    lastUpdate: "Today · 08:04 AM",
  },
  {
    id: "priya-iyer",
    full_name: "Priya Iyer",
    email: "priya.iyer@btic.co",
    team: "programming",
    accessRole: "attendee",
    status: "active",
    source: "Master upload · Clean",
    lastUpdate: "Today · 09:00 AM",
  },
  {
    id: "renee-yang",
    full_name: "Renee Yang",
    email: "renee.yang@btic.co",
    team: "logistics",
    accessRole: "attendee",
    status: "invited",
    source: "Self-service RSVP",
    lastUpdate: "Today · 08:11 AM",
  },
  {
    id: "samir-holt",
    full_name: "Samir Holt",
    email: "samir.holt@btic.co",
    team: "logistics",
    accessRole: "staff",
    staffType: "logistics-fleet",
    status: "active",
    source: "Master upload · Clean",
    lastUpdate: "Today · 09:20 AM",
  },
  {
    id: "ivy-lam",
    full_name: "Ivy Lam",
    email: "ivy.lam@btic.co",
    team: "hospitality",
    accessRole: "attendee",
    status: "revoked",
    source: "Manual revoke",
    lastUpdate: "Yesterday · 05:10 PM",
  },
  {
    id: "ethan-brooks",
    full_name: "Ethan Brooks",
    email: "ethan.brooks@btic.co",
    team: "operations",
    accessRole: "staff",
    staffType: "ops-runner",
    status: "active",
    source: "Master upload · Clean",
    lastUpdate: "Today · 08:58 AM",
  },
  {
    id: "noor-kamal",
    full_name: "Noor Kamal",
    email: "noor.kamal@btic.co",
    team: "programming",
    accessRole: "attendee",
    status: "active",
    source: "Team import",
    lastUpdate: "Today · 08:01 AM",
  },
] as const;

const statusStyles = {
  active: {
    label: "Active access",
    badge: "bg-emerald-500/10 text-emerald-300 border border-emerald-500/40",
    copy: "Person can log in and scan badges right now.",
  },
  invited: {
    label: "Invite pending",
    badge: "bg-amber-500/10 text-amber-300 border border-amber-500/40",
    copy: "Waiting on verification email or staff approval.",
  },
  revoked: {
    label: "Access revoked",
    badge: "bg-rose-500/10 text-rose-300 border border-rose-500/40",
    copy: "Login blocked until access is restored.",
  },
};

const accessStyles = {
  staff: {
    label: "Staff",
    badge: "bg-sky-500/10 text-sky-300 border border-sky-500/40",
  },
  attendee: {
    label: "Attendee",
    badge: "bg-slate-500/10 text-slate-300 border border-slate-500/40",
  },
};

export { teams, staffTypes, peopleDirectory, statusStyles, accessStyles };
