import { AccessStatus, Grade, Role, Subteam, User } from "@/schemas/database";

const teams: Record<Subteam, string> = {
  logistics: "Logistics",
  registration: "Registration",
  technology: "Technology",
  security: "Security",
  operations: "Operations",
  finance: "Finance",
};

const roles: Record<Role, string> = {
  admin: "Admin",
  staff: "Staff",
  attendee: "Attendee",
};

const accessStatuses: Record<AccessStatus, string> = {
  active: "Active",
  invited: "Invited",
  revoked: "Revoked",
};

const grades: Record<Grade, string> = {
  freshman: "Freshman",
  sophomore: "Sophomore",
  junior: "Junior",
  senior: "Senior",
  graduate: "Graduate",
  other: "Other",
};

const peopleDirectory: User[] = [
  {
    uid: crypto.randomUUID().toString(),
    displayName: "Alex Chen",
    email: "alex.chen@btic.co",
    subteam: "operations",
    role: "staff",
    accessStatus: "active",
    fullName: "Alex Chen",
    school: "Georgia Tech",
    grade: "graduate",
    company: "BTIC Ops Command",
    phoneNumber: "+1 (555) 010-1001",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    eventIds: [],
    roomNumber: "",
    qrCode: "",
    helpRequests: [],
    providerId: "google.com",
    emailVerified: true,
    photoURL: "",
  },
  {
    uid: crypto.randomUUID().toString(),
    displayName: "Maya Patel",
    email: "maya.patel@btic.co",
    subteam: "technology",
    role: "staff",
    accessStatus: "active",
    fullName: "Maya Patel",
    school: "UCLA",
    grade: "senior",
    company: "StoryCraft Labs",
    phoneNumber: "+1 (555) 010-1002",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    eventIds: [],
    roomNumber: "",
    qrCode: "",
    helpRequests: [],
    providerId: "google.com",
    emailVerified: true,
    photoURL: "",
  },
  {
    uid: crypto.randomUUID().toString(),
    displayName: "Leo Carter",
    email: "leo.carter@btic.co",
    subteam: "operations",
    role: "staff",
    accessStatus: "active",
    fullName: "Leo Carter",
    school: "NYU",
    grade: "graduate",
    company: "GatherGood",
    phoneNumber: "+1 (555) 010-1003",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    eventIds: [],
    roomNumber: "",
    qrCode: "",
    helpRequests: [],
    providerId: "google.com",
    emailVerified: true,
    photoURL: "",
  },
  {
    uid: crypto.randomUUID().toString(),
    displayName: "Lara Cho",
    email: "lara.cho@btic.co",
    subteam: "security",
    role: "staff",
    accessStatus: "active",
    fullName: "Lara Cho",
    school: "University of Michigan",
    grade: "senior",
    company: "Sentinel Partners",
    phoneNumber: "+1 (555) 010-1004",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    eventIds: [],
    roomNumber: "",
    qrCode: "",
    helpRequests: [],
    providerId: "google.com",
    emailVerified: true,
    photoURL: "",
  },
  {
    uid: crypto.randomUUID().toString(),
    displayName: "Opal Reed",
    email: "opal.reed@btic.co",
    subteam: "logistics",
    role: "staff",
    accessStatus: "active",
    fullName: "Opal Reed",
    school: "MIT",
    grade: "graduate",
    company: "FleetFlow",
    phoneNumber: "+1 (555) 010-1005",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    eventIds: [],
    roomNumber: "",
    qrCode: "",
    helpRequests: [],
    providerId: "google.com",
    emailVerified: true,
    photoURL: "",
  },
  {
    uid: crypto.randomUUID().toString(),
    displayName: "Natalie Young",
    email: "natalie.young@btic.co",
    subteam: "technology",
    role: "attendee",
    accessStatus: "invited",
    fullName: "Natalie Young",
    school: "UC Berkeley",
    grade: "junior",
    company: "Nimbus Media",
    phoneNumber: "+1 (555) 010-1006",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    eventIds: [],
    roomNumber: "",
    qrCode: "",
    helpRequests: [],
    providerId: "google.com",
    emailVerified: true,
    photoURL: "",
  },
  {
    uid: crypto.randomUUID().toString(),
    displayName: "Jamie Bowen",
    email: "jamie.bowen@btic.co",
    subteam: "operations",
    role: "attendee",
    accessStatus: "active",
    fullName: "Jamie Bowen",
    school: "University of Florida",
    grade: "senior",
    company: "Brightline",
    phoneNumber: "+1 (555) 010-1007",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    eventIds: [],
    roomNumber: "",
    qrCode: "",
    helpRequests: [],
    providerId: "google.com",
    emailVerified: true,
    photoURL: "",
  },
];

const statusStyles = {
  active: {
    label: "Active access",
    badge: "bg-emerald-500/10 text-emerald-300 border border-emerald-500/40",
    copy: "Person can log in and scan badges right now.",
  },
  invited: {
    label: "Invite pending",
    badge: "bg-amber-500/10 text-amber-300 border border-amber-500/40",
    copy: "Waiting on verification email or staff approval.",
  },
  revoked: {
    label: "Access revoked",
    badge: "bg-rose-500/10 text-rose-300 border border-rose-500/40",
    copy: "Login blocked until access is restored.",
  },
};

const accessStyles = {
  admin: {
    label: "Admin",
    badge: "bg-violet-500/10 text-violet-200 border border-violet-500/40",
  },
  staff: {
    label: "Staff",
    badge: "bg-sky-500/10 text-sky-300 border border-sky-500/40",
  },
  attendee: {
    label: "Attendee",
    badge: "bg-slate-500/10 text-slate-300 border border-slate-500/40",
  },
};

export { teams, roles, accessStatuses, grades, peopleDirectory, statusStyles, accessStyles };
