import type { Metadata } from "next";
import "./globals.css";

import { Sora } from "next/font/google";
const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sora.variable} antialiased`}>
      <body>{children}</body>
    </html>
  );
}
